-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.achievement
(
    achievement_id text COLLATE pg_catalog."default" NOT NULL,
    code text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    rarity text COLLATE pg_catalog."default",
    reward_json jsonb,
    is_hidden boolean NOT NULL DEFAULT false,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT achievement_pkey PRIMARY KEY (achievement_id),
    CONSTRAINT achievement_code_key UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.battle_log
(
    battle_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default",
    enemy_id text COLLATE pg_catalog."default",
    result text COLLATE pg_catalog."default",
    reward_json jsonb,
    created_at timestamp with time zone,
    enemy_power integer,
    enemy_type text COLLATE pg_catalog."default",
    CONSTRAINT battle_log_pkey PRIMARY KEY (battle_id)
);

CREATE TABLE IF NOT EXISTS public."character"
(
    character_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    race text COLLATE pg_catalog."default",
    rank_id text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    character_path text COLLATE pg_catalog."default",
    age integer,
    is_alive boolean,
    CONSTRAINT character_pkey PRIMARY KEY (character_id)
);

CREATE TABLE IF NOT EXISTS public.character_achievement
(
    character_id text COLLATE pg_catalog."default" NOT NULL,
    achievement_id text COLLATE pg_catalog."default" NOT NULL,
    progress integer NOT NULL DEFAULT 0,
    target_value integer,
    unlocked_at timestamp with time zone,
    claimed_at timestamp with time zone,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'locked'::text,
    metadata_json jsonb,
    CONSTRAINT character_achievement_pkey PRIMARY KEY (character_id, achievement_id)
);

CREATE TABLE IF NOT EXISTS public.character_quest
(
    character_id text COLLATE pg_catalog."default" NOT NULL,
    quest_id text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default",
    progress text COLLATE pg_catalog."default",
    updated_at timestamp with time zone,
    CONSTRAINT character_quest_pkey PRIMARY KEY (character_id, quest_id)
);

CREATE TABLE IF NOT EXISTS public.character_skill
(
    character_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    level integer,
    unlocked_at timestamp with time zone,
    discovery_method text COLLATE pg_catalog."default",
    CONSTRAINT character_skill_pkey PRIMARY KEY (character_id, skill_id)
);

CREATE TABLE IF NOT EXISTS public.character_stats
(
    defense integer,
    strength integer,
    speed integer,
    mana integer,
    energy integer,
    level integer,
    exp integer,
    gold bigint,
    hp integer,
    hunting_points integer,
    black_knowledge_level integer,
    intelligence integer,
    luck integer,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT player_stats_pkey PRIMARY KEY (character_id)
        INCLUDE(character_id)
);

CREATE TABLE IF NOT EXISTS public.civilizations
(
    id serial NOT NULL,
    slug character varying(50) COLLATE pg_catalog."default" NOT NULL,
    name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    starting_stats_bonus jsonb DEFAULT '{}'::jsonb,
    culture_type character varying(50) COLLATE pg_catalog."default",
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    starting_location_id text COLLATE pg_catalog."default",
    CONSTRAINT civilizations_pkey PRIMARY KEY (id),
    CONSTRAINT civilizations_slug_key UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.clan
(
    clan_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    leader_character_id text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT clan_pkey PRIMARY KEY (clan_id)
);

CREATE TABLE IF NOT EXISTS public.clan_member
(
    clan_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    member_role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'member'::text,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    left_at timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT clan_member_pkey PRIMARY KEY (clan_id, character_id)
);

CREATE TABLE IF NOT EXISTS public.cooldowns
(
    cooldown_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    skill_id text COLLATE pg_catalog."default",
    action_type text COLLATE pg_catalog."default" NOT NULL,
    target_id text COLLATE pg_catalog."default",
    started_at timestamp with time zone NOT NULL DEFAULT now(),
    ends_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    metadata_json jsonb,
    CONSTRAINT cooldowns_pkey PRIMARY KEY (cooldown_id)
);

CREATE TABLE IF NOT EXISTS public.dungeon
(
    dungeon_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    location_id text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT dungeon_pkey PRIMARY KEY (dungeon_id)
);

CREATE TABLE IF NOT EXISTS public.dungeon_enemy_config
(
    dungeon_id text COLLATE pg_catalog."default" NOT NULL,
    enemy_id text COLLATE pg_catalog."default" NOT NULL,
    min_count integer,
    max_count integer,
    spawn_weight integer,
    CONSTRAINT dungeon_enemy_config_pkey PRIMARY KEY (dungeon_id, enemy_id)
);

CREATE TABLE IF NOT EXISTS public.dungeon_item_config
(
    dungeon_id text COLLATE pg_catalog."default" NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    min_count integer,
    max_count integer,
    dnx_weight integer,
    CONSTRAINT dungeon_item_config_pkey PRIMARY KEY (dungeon_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.economy_ledger
(
    ledger_id text COLLATE pg_catalog."default" NOT NULL,
    wallet_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default",
    transaction_type text COLLATE pg_catalog."default" NOT NULL,
    currency_type text COLLATE pg_catalog."default" NOT NULL,
    amount bigint NOT NULL,
    balance_before bigint,
    balance_after bigint,
    source_type text COLLATE pg_catalog."default",
    source_id text COLLATE pg_catalog."default",
    note text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT economy_ledger_pkey PRIMARY KEY (ledger_id)
);

CREATE TABLE IF NOT EXISTS public.enemy
(
    enemy_id text COLLATE pg_catalog."default" NOT NULL,
    type text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    rank_id text COLLATE pg_catalog."default",
    loot_json jsonb,
    location_id text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    rarity_weight integer,
    origin_world text COLLATE pg_catalog."default",
    CONSTRAINT enemy_pkey PRIMARY KEY (enemy_id)
);

CREATE TABLE IF NOT EXISTS public.enemy_instance
(
    instance_id text COLLATE pg_catalog."default" NOT NULL,
    enemy_id text COLLATE pg_catalog."default",
    level integer,
    hp integer,
    mana integer,
    location_id text COLLATE pg_catalog."default",
    extra_properties text COLLATE pg_catalog."default",
    energy integer,
    spawn_at timestamp with time zone,
    CONSTRAINT enemy_instance_pkey PRIMARY KEY (instance_id)
);

CREATE TABLE IF NOT EXISTS public.enemy_stats
(
    enemy_id text COLLATE pg_catalog."default" NOT NULL,
    strength integer,
    speed integer,
    mana integer,
    energy integer,
    hp integer,
    luck integer,
    CONSTRAINT enemy_stats_pkey PRIMARY KEY (enemy_id)
);

CREATE TABLE IF NOT EXISTS public.equipment
(
    equipment_id text COLLATE pg_catalog."default" NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    slot_type text COLLATE pg_catalog."default" NOT NULL,
    enhancement_level integer NOT NULL DEFAULT 0,
    durability integer,
    max_durability integer,
    equipped_at timestamp with time zone NOT NULL DEFAULT now(),
    unequipped_at timestamp with time zone,
    is_equipped boolean NOT NULL DEFAULT true,
    extra_json jsonb,
    CONSTRAINT equipment_pkey PRIMARY KEY (equipment_id),
    CONSTRAINT equipment_item_id_key UNIQUE (item_id)
);

CREATE TABLE IF NOT EXISTS public.event_history
(
    player_id text COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default",
    event_data jsonb,
    created_at time with time zone,
    event_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT event_history_pkey PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS public.family_background
(
    background_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    starting_items jsonb,
    start_skill jsonb,
    spawn_weight integer,
    CONSTRAINT family_background_pkey PRIMARY KEY (background_id)
);

CREATE TABLE IF NOT EXISTS public.guild
(
    guild_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    leader_character_id text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    motto text COLLATE pg_catalog."default",
    level integer NOT NULL DEFAULT 1,
    exp bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT guild_pkey PRIMARY KEY (guild_id)
);

CREATE TABLE IF NOT EXISTS public.guild_member
(
    guild_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    member_role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'member'::text,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    left_at timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT guild_member_pkey PRIMARY KEY (guild_id, character_id)
);

CREATE TABLE IF NOT EXISTS public.inventory
(
    character_id text COLLATE pg_catalog."default" NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    quantity integer,
    CONSTRAINT inventory_pkey PRIMARY KEY (character_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.item
(
    item_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    rarity text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    effect_json jsonb,
    rarity_weight integer,
    CONSTRAINT item_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.location
(
    location_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    danger_level integer,
    region_type text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT location_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public.location_feature
(
    feature_id text COLLATE pg_catalog."default" NOT NULL,
    location_id text COLLATE pg_catalog."default",
    name text COLLATE pg_catalog."default",
    rarity text COLLATE pg_catalog."default",
    effect_json jsonb,
    effect_region text COLLATE pg_catalog."default",
    weight integer,
    CONSTRAINT location_feature_pkey PRIMARY KEY (feature_id)
);

CREATE TABLE IF NOT EXISTS public.login_history
(
    login_history_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default" NOT NULL,
    session_id text COLLATE pg_catalog."default",
    login_at timestamp with time zone NOT NULL DEFAULT now(),
    logout_at timestamp with time zone,
    ip_address text COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    login_status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'success'::text,
    failure_reason text COLLATE pg_catalog."default",
    CONSTRAINT login_history_pkey PRIMARY KEY (login_history_id)
);

CREATE TABLE IF NOT EXISTS public.market_listing
(
    listing_id text COLLATE pg_catalog."default" NOT NULL,
    seller_id text COLLATE pg_catalog."default" NOT NULL,
    item_instance_id text COLLATE pg_catalog."default",
    item_id text COLLATE pg_catalog."default" NOT NULL,
    quantity integer DEFAULT 1,
    price_per_unit bigint NOT NULL,
    currency_type text COLLATE pg_catalog."default" DEFAULT 'gold'::text,
    created_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone NOT NULL,
    is_sold boolean DEFAULT false,
    is_cancelled boolean DEFAULT false,
    CONSTRAINT market_listing_pkey PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS public.message
(
    message_id text COLLATE pg_catalog."default" NOT NULL,
    sender_player_id text COLLATE pg_catalog."default",
    receiver_player_id text COLLATE pg_catalog."default",
    sender_character_id text COLLATE pg_catalog."default",
    receiver_character_id text COLLATE pg_catalog."default",
    subject text COLLATE pg_catalog."default",
    body text COLLATE pg_catalog."default",
    attachment_json jsonb,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'sent'::text,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    read_at timestamp with time zone,
    CONSTRAINT message_pkey PRIMARY KEY (message_id)
);

CREATE TABLE IF NOT EXISTS public.notification
(
    notification_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default",
    notification_type text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default",
    payload_json jsonb,
    is_read boolean NOT NULL DEFAULT false,
    read_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT notification_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.npc
(
    npc_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default",
    npc_type text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    base_location_id text COLLATE pg_catalog."default",
    is_killable boolean DEFAULT false,
    dialogue_json jsonb,
    extra_properties jsonb,
    CONSTRAINT npc_pkey PRIMARY KEY (npc_id)
);

CREATE TABLE IF NOT EXISTS public.npc_interaction_rule
(
    rule_id text COLLATE pg_catalog."default" NOT NULL,
    npc_id text COLLATE pg_catalog."default" NOT NULL,
    required_quest_id text COLLATE pg_catalog."default",
    required_level integer,
    trigger_event text COLLATE pg_catalog."default",
    response_text text COLLATE pg_catalog."default",
    reward_json jsonb,
    CONSTRAINT npc_interaction_rule_pkey PRIMARY KEY (rule_id)
);

CREATE TABLE IF NOT EXISTS public.npc_merchant_stock
(
    npc_id text COLLATE pg_catalog."default" NOT NULL,
    item_id text COLLATE pg_catalog."default" NOT NULL,
    price bigint NOT NULL,
    currency_type text COLLATE pg_catalog."default" DEFAULT 'gold'::text,
    stock_quantity integer DEFAULT '-1'::integer,
    refresh_time interval,
    CONSTRAINT npc_merchant_stock_pkey PRIMARY KEY (npc_id, item_id)
);

CREATE TABLE IF NOT EXISTS public.npc_stats
(
    npc_id text COLLATE pg_catalog."default" NOT NULL,
    defense integer,
    strength integer,
    speed integer,
    mana integer,
    energy integer,
    level integer,
    exp integer,
    gold integer,
    hp integer,
    hunting_points integer,
    black_knowledge_level integer,
    intelligence integer,
    luck integer,
    CONSTRAINT npc_stats_pkey PRIMARY KEY (npc_id)
);

CREATE TABLE IF NOT EXISTS public.party
(
    party_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    leader_character_id text COLLATE pg_catalog."default" NOT NULL,
    party_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'party'::text,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT party_pkey PRIMARY KEY (party_id)
);

CREATE TABLE IF NOT EXISTS public.party_member
(
    party_id text COLLATE pg_catalog."default" NOT NULL,
    character_id text COLLATE pg_catalog."default" NOT NULL,
    member_role text COLLATE pg_catalog."default" NOT NULL DEFAULT 'member'::text,
    joined_at timestamp with time zone NOT NULL DEFAULT now(),
    left_at timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    CONSTRAINT party_member_pkey PRIMARY KEY (party_id, character_id)
);

CREATE TABLE IF NOT EXISTS public.player
(
    player_id text COLLATE pg_catalog."default" NOT NULL,
    telegram_id text COLLATE pg_catalog."default",
    username text COLLATE pg_catalog."default",
    created_at timestamp with time zone,
    last_active timestamp with time zone,
    role text COLLATE pg_catalog."default",
    is_banned boolean,
    CONSTRAINT users_pkey PRIMARY KEY (player_id)
);

CREATE TABLE IF NOT EXISTS public.player_mail
(
    mail_id text COLLATE pg_catalog."default" NOT NULL,
    receiver_id text COLLATE pg_catalog."default" NOT NULL,
    sender_name text COLLATE pg_catalog."default" DEFAULT 'System'::text,
    subject text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default",
    attachment_json jsonb,
    is_read boolean DEFAULT false,
    is_claimed boolean DEFAULT false,
    sent_at timestamp with time zone DEFAULT now(),
    expires_at timestamp with time zone,
    CONSTRAINT player_mail_pkey PRIMARY KEY (mail_id)
);

CREATE TABLE IF NOT EXISTS public.player_session
(
    session_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default" NOT NULL,
    telegram_chat_id text COLLATE pg_catalog."default",
    ip_address text COLLATE pg_catalog."default",
    user_agent text COLLATE pg_catalog."default",
    login_at timestamp with time zone NOT NULL DEFAULT now(),
    last_seen_at timestamp with time zone,
    logout_at timestamp with time zone,
    is_active boolean NOT NULL DEFAULT true,
    refresh_token_hash text COLLATE pg_catalog."default",
    CONSTRAINT player_session_pkey PRIMARY KEY (session_id)
);

CREATE TABLE IF NOT EXISTS public.player_state
(
    player_id text COLLATE pg_catalog."default",
    current_location_id text COLLATE pg_catalog."default",
    current_region_id text COLLATE pg_catalog."default",
    energy integer,
    step_counter integer,
    last_event_type text COLLATE pg_catalog."default",
    seed_value integer,
    last_location_change text COLLATE pg_catalog."default",
    last_event_at timestamp with time zone
);

CREATE TABLE IF NOT EXISTS public.player_wallet
(
    wallet_id text COLLATE pg_catalog."default" NOT NULL,
    player_id text COLLATE pg_catalog."default" NOT NULL,
    gold_balance bigint NOT NULL DEFAULT 0,
    gem_balance bigint NOT NULL DEFAULT 0,
    silver_balance bigint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT player_wallet_pkey PRIMARY KEY (wallet_id),
    CONSTRAINT player_wallet_player_id_key UNIQUE (player_id)
);

CREATE TABLE IF NOT EXISTS public.quest
(
    quest_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    location_id text COLLATE pg_catalog."default",
    difficulty_rank text COLLATE pg_catalog."default",
    reward_json jsonb,
    description text COLLATE pg_catalog."default",
    CONSTRAINT quest_pkey PRIMARY KEY (quest_id)
);

CREATE TABLE IF NOT EXISTS public.race
(
    race_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    talent_modifiers jsonb,
    description text COLLATE pg_catalog."default",
    spawn_weight integer,
    civilization_id integer,
    base_stats_modifier jsonb,
    CONSTRAINT race_pkey PRIMARY KEY (race_id)
);

CREATE TABLE IF NOT EXISTS public.rank
(
    rank_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    power_multiplier text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT rank_pkey PRIMARY KEY (rank_id)
);

CREATE TABLE IF NOT EXISTS public.skill
(
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    type text COLLATE pg_catalog."default",
    mana_cost integer,
    cooldown integer,
    CONSTRAINT skill_pkey PRIMARY KEY (skill_id)
);

CREATE TABLE IF NOT EXISTS public.skill_discovery_rule
(
    skill_id text COLLATE pg_catalog."default" NOT NULL,
    activity_type text COLLATE pg_catalog."default" NOT NULL,
    base_chance text COLLATE pg_catalog."default",
    rarity text COLLATE pg_catalog."default" NOT NULL,
    talent_bonus jsonb,
    CONSTRAINT skill_discovery_rule_pkey PRIMARY KEY (skill_id, activity_type, rarity)
);

CREATE TABLE IF NOT EXISTS public.world_environment
(
    environment_id text COLLATE pg_catalog."default" NOT NULL,
    location_id text COLLATE pg_catalog."default",
    weather_type text COLLATE pg_catalog."default" NOT NULL,
    active_buffs_json jsonb,
    started_at timestamp with time zone DEFAULT now(),
    ends_at timestamp with time zone,
    CONSTRAINT world_environment_pkey PRIMARY KEY (environment_id)
);

CREATE TABLE IF NOT EXISTS public.world_events
(
    id serial NOT NULL,
    event_type character varying COLLATE pg_catalog."default",
    description character varying COLLATE pg_catalog."default",
    created_at timestamp without time zone,
    CONSTRAINT world_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.world_links
(
    id serial NOT NULL,
    source_location_id text COLLATE pg_catalog."default",
    target_location_id text COLLATE pg_catalog."default",
    link_type character varying(50) COLLATE pg_catalog."default" DEFAULT 'portal'::character varying,
    is_active boolean DEFAULT true,
    mana_cost integer DEFAULT 0,
    metadata jsonb,
    required_item_id text COLLATE pg_catalog."default",
    CONSTRAINT world_links_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.world_objects
(
    id serial NOT NULL,
    location_id text COLLATE pg_catalog."default",
    object_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    state jsonb,
    interaction_logic character varying(100) COLLATE pg_catalog."default",
    last_interacted_at timestamp with time zone,
    respawn_time_seconds integer,
    CONSTRAINT world_objects_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.world_rules
(
    id serial NOT NULL,
    rule_key character varying(100) COLLATE pg_catalog."default" NOT NULL,
    rule_value numeric(10, 2) NOT NULL,
    affected_location_id text COLLATE pg_catalog."default",
    affected_civilization_id integer,
    expires_at timestamp with time zone,
    CONSTRAINT world_rules_pkey PRIMARY KEY (id, rule_key, rule_value),
    CONSTRAINT world_rules_rule_key_key UNIQUE (rule_key)
);

ALTER TABLE IF EXISTS public.battle_log
    ADD CONSTRAINT battle_log_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.battle_log
    ADD CONSTRAINT battle_log_enemy_id_fkey FOREIGN KEY (enemy_id)
    REFERENCES public.enemy (enemy_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."character"
    ADD CONSTRAINT character_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public."character"
    ADD CONSTRAINT character_rank_id_fkey FOREIGN KEY (rank_id)
    REFERENCES public.rank (rank_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.character_achievement
    ADD CONSTRAINT character_achievement_achievement_id_fkey FOREIGN KEY (achievement_id)
    REFERENCES public.achievement (achievement_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.character_achievement
    ADD CONSTRAINT character_achievement_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.character_quest
    ADD CONSTRAINT character_quest_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.character_quest
    ADD CONSTRAINT character_quest_quest_id_fkey FOREIGN KEY (quest_id)
    REFERENCES public.quest (quest_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.character_skill
    ADD CONSTRAINT character_skill_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.character_skill
    ADD CONSTRAINT character_skill_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skill (skill_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.character_stats
    ADD CONSTRAINT fk_player_stats_character FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS player_stats_pkey
    ON public.character_stats(character_id);


ALTER TABLE IF EXISTS public.character_stats
    ADD CONSTRAINT player_stats_charecter_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;
CREATE INDEX IF NOT EXISTS player_stats_pkey
    ON public.character_stats(character_id);


ALTER TABLE IF EXISTS public.civilizations
    ADD CONSTRAINT fk_civilizations_starting_location FOREIGN KEY (starting_location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.clan
    ADD CONSTRAINT clan_leader_character_id_fkey FOREIGN KEY (leader_character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.clan_member
    ADD CONSTRAINT clan_member_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.clan_member
    ADD CONSTRAINT clan_member_clan_id_fkey FOREIGN KEY (clan_id)
    REFERENCES public.clan (clan_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cooldowns
    ADD CONSTRAINT cooldowns_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.cooldowns
    ADD CONSTRAINT cooldowns_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skill (skill_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.dungeon_enemy_config
    ADD CONSTRAINT dungeon_enemy_config_dungeon_id_fkey FOREIGN KEY (dungeon_id)
    REFERENCES public.dungeon (dungeon_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.dungeon_enemy_config
    ADD CONSTRAINT dungeon_enemy_config_enemy_id_fkey FOREIGN KEY (enemy_id)
    REFERENCES public.enemy (enemy_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.dungeon_item_config
    ADD CONSTRAINT dungeon_item_config_dungeon_id_fkey FOREIGN KEY (dungeon_id)
    REFERENCES public.dungeon (dungeon_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.dungeon_item_config
    ADD CONSTRAINT dungeon_item_config_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.economy_ledger
    ADD CONSTRAINT economy_ledger_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.economy_ledger
    ADD CONSTRAINT economy_ledger_wallet_id_fkey FOREIGN KEY (wallet_id)
    REFERENCES public.player_wallet (wallet_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enemy
    ADD CONSTRAINT enemy_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enemy
    ADD CONSTRAINT enemy_rank_id_fkey FOREIGN KEY (rank_id)
    REFERENCES public.rank (rank_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enemy_instance
    ADD CONSTRAINT "enemy_instance_enemy_id _fkey" FOREIGN KEY (enemy_id)
    REFERENCES public.enemy (enemy_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enemy_instance
    ADD CONSTRAINT enemy_instance_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.enemy_stats
    ADD CONSTRAINT enemy_stats_enemy_id_fkey FOREIGN KEY (enemy_id)
    REFERENCES public.enemy (enemy_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;
CREATE INDEX IF NOT EXISTS enemy_stats_pkey
    ON public.enemy_stats(enemy_id);


ALTER TABLE IF EXISTS public.equipment
    ADD CONSTRAINT equipment_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.equipment
    ADD CONSTRAINT equipment_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS equipment_item_id_key
    ON public.equipment(item_id);


ALTER TABLE IF EXISTS public.event_history
    ADD CONSTRAINT event_history_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.guild
    ADD CONSTRAINT guild_leader_character_id_fkey FOREIGN KEY (leader_character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.guild_member
    ADD CONSTRAINT guild_member_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.guild_member
    ADD CONSTRAINT guild_member_guild_id_fkey FOREIGN KEY (guild_id)
    REFERENCES public.guild (guild_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT inventory_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.inventory
    ADD CONSTRAINT inventory_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.location_feature
    ADD CONSTRAINT location_feature_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.login_history
    ADD CONSTRAINT login_history_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.login_history
    ADD CONSTRAINT login_history_session_id_fkey FOREIGN KEY (session_id)
    REFERENCES public.player_session (session_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.market_listing
    ADD CONSTRAINT market_seller_fkey FOREIGN KEY (seller_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.message
    ADD CONSTRAINT message_receiver_character_id_fkey FOREIGN KEY (receiver_character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.message
    ADD CONSTRAINT message_receiver_player_id_fkey FOREIGN KEY (receiver_player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.message
    ADD CONSTRAINT message_sender_character_id_fkey FOREIGN KEY (sender_character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.message
    ADD CONSTRAINT message_sender_player_id_fkey FOREIGN KEY (sender_player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.notification
    ADD CONSTRAINT notification_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notification
    ADD CONSTRAINT notification_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.npc
    ADD CONSTRAINT npc_location_fkey FOREIGN KEY (base_location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.npc_interaction_rule
    ADD CONSTRAINT rule_npc_fkey FOREIGN KEY (npc_id)
    REFERENCES public.npc (npc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.npc_merchant_stock
    ADD CONSTRAINT stock_item_fkey FOREIGN KEY (item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.npc_merchant_stock
    ADD CONSTRAINT stock_npc_fkey FOREIGN KEY (npc_id)
    REFERENCES public.npc (npc_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.party
    ADD CONSTRAINT party_leader_character_id_fkey FOREIGN KEY (leader_character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.party_member
    ADD CONSTRAINT party_member_character_id_fkey FOREIGN KEY (character_id)
    REFERENCES public."character" (character_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.party_member
    ADD CONSTRAINT party_member_party_id_fkey FOREIGN KEY (party_id)
    REFERENCES public.party (party_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_mail
    ADD CONSTRAINT mail_receiver_fkey FOREIGN KEY (receiver_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_session
    ADD CONSTRAINT player_session_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_state
    ADD CONSTRAINT player_state_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.player_wallet
    ADD CONSTRAINT player_wallet_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.player (player_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS player_wallet_player_id_key
    ON public.player_wallet(player_id);


ALTER TABLE IF EXISTS public.quest
    ADD CONSTRAINT quest_difficulty_rank_fkey FOREIGN KEY (difficulty_rank)
    REFERENCES public.rank (rank_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.quest
    ADD CONSTRAINT quest_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.race
    ADD CONSTRAINT race_civilization_id_fkey FOREIGN KEY (civilization_id)
    REFERENCES public.civilizations (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.skill_discovery_rule
    ADD CONSTRAINT skill_discovery_rule_skill_id_fkey FOREIGN KEY (skill_id)
    REFERENCES public.skill (skill_id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.world_links
    ADD CONSTRAINT fk_world_links_required_item FOREIGN KEY (required_item_id)
    REFERENCES public.item (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.world_links
    ADD CONSTRAINT world_links_source_location_id_fkey FOREIGN KEY (source_location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.world_links
    ADD CONSTRAINT world_links_target_location_id_fkey FOREIGN KEY (target_location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.world_objects
    ADD CONSTRAINT world_objects_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.world_rules
    ADD CONSTRAINT world_rules_affected_civilization_id_fkey FOREIGN KEY (affected_civilization_id)
    REFERENCES public.civilizations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.world_rules
    ADD CONSTRAINT world_rules_affected_location_id_fkey FOREIGN KEY (affected_location_id)
    REFERENCES public.location (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;